// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dilikeo.service.api;

import com.dilikeo.domain.DatosVendedor;
import com.dilikeo.service.api.DatosVendedorService;
import io.springlets.data.domain.GlobalSearch;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

privileged aspect DatosVendedorService_Roo_Service {
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return DatosVendedor
     */
    public abstract DatosVendedor DatosVendedorService.findOne(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param datosVendedor
     */
    public abstract void DatosVendedorService.delete(DatosVendedor datosVendedor);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entities
     * @return List
     */
    public abstract List<DatosVendedor> DatosVendedorService.save(Iterable<DatosVendedor> entities);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     */
    public abstract void DatosVendedorService.delete(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param entity
     * @return DatosVendedor
     */
    public abstract DatosVendedor DatosVendedorService.save(DatosVendedor entity);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param id
     * @return DatosVendedor
     */
    public abstract DatosVendedor DatosVendedorService.findOneForUpdate(Long id);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @return List
     */
    public abstract List<DatosVendedor> DatosVendedorService.findAll(Iterable<Long> ids);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return List
     */
    public abstract List<DatosVendedor> DatosVendedorService.findAll();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Long
     */
    public abstract long DatosVendedorService.count();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public abstract Page<DatosVendedor> DatosVendedorService.findAll(GlobalSearch globalSearch, Pageable pageable);
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param ids
     * @param globalSearch
     * @param pageable
     * @return Page
     */
    public abstract Page<DatosVendedor> DatosVendedorService.findAllByIdsIn(List<Long> ids, GlobalSearch globalSearch, Pageable pageable);
    
}
