// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dilikeo.repository;

import com.dilikeo.repository.DevolucionesRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DevolucionesRepository_Roo_Jpa_Repository {
    
    declare @type: DevolucionesRepository: @Transactional(readOnly = true);
    
}
